### PR TITLE
Add an output to flag a successful deployment

### PR DESCRIPTION
**Pull request by johngeorgewright**
Adding an output variable to flag if a deployment was successful. 

This can be helpful in situation when one wants to run jobs only if a deployment was successful.

### CODE REVIEW

**Comment by SamKirkland** [comment]
Very interesting.

Do you know if we need to set a output in order for this to work? Or will `${{ success() }}` work automatically?

[Status docs here](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-status-check-functions) If status doesn't work It might be due to issue #123

**Comment by johngeorgewright** [comment]
Damn. I sad I didn't find the docs on status functions before I did this... but I'm glad that I now know!

I can confirm that this action works just fine with these status functions. Happy to close this, unless you'd like me rework the example to use status functions.

**Comment by SamKirkland** [comment]
I've assigned this to myself as a documentation issue. I'll close when I get to updating the readme

**Comment by SamKirkland** [comment]
Closing now with v4.1.0 the action throws when not successful. I did not update the readme because this is expected behavior.

**Pull request closed without merging**
