### PR TITLE
Fix problem setting up known-hosts

### PR DESCRIPTION
**Pull request by ciex**
Hey Sam, thank you for this script. 

I had some problems setting up with the `known-hosts` argument. I found it be missing from the `action.yml`, which lead to a misleading error while running the action. I added it to `action.yml`.

Also, the example for that argument from the documentation was missing the  actual known-hosts argument, so I added that as well. I had to add the domain name in frony of "ssh-rsa" for it to work for me. My "domain" is just an IP address, I hope the syntax I added here works. It's what `ssh-keyscan` prints out when run on the domain that's used elsewhere in the examples. 

Hope this helps someone else in the future. Cheers

### CODE REVIEW

**Comment by surjithctly** [comment]
@ciex  Can you check #98 ? I think the issue is related to this pull request.

**Comment by ciex** [comment]
@surjithctly That looks exactly like the error I was fixing here for me. Are you sure that you are using a version that includes this change?

**Comment by surjithctly** [comment]
@ciex I have used v3.1.1, Not sure if that's included. If not, how do I do that?

**Comment by HannesOberreiter** [comment]
@surjithctly you can use the master branch `uses: SamKirkland/FTP-Deploy-Action@master`

**Comment by patrickbussmann** [comment]
Had the same isse - `@master` works. Thank you!

**Pull request merged**
