### PR TITLE
known_hosts support

### PR DESCRIPTION
**Pull request by apokalyptik**
fix for https://github.com/SamKirkland/FTP-Deploy-Action/issues/54

### CODE REVIEW

**Comment by SamKirkland** [comment]
This is great! Thanks for submitting this PR!
I have updated the `main.ts` file of your PR. Please see the [notes](https://github.com/SamKirkland/FTP-Deploy-Action/pull/55/commits/af948b80607eb0d13a18a3c2f03d6d238dd8f68e) on my changes.

Before I can accept this PR can you please:

1. Update the `README.md` file with some documentation on this new argument **and** add an example.
2. Rebuild with my changes so `index.js` get re-generated.


If you have any questions let me know!

**Comment by apokalyptik** [comment]
I have done the requested work. Thanks for the review and edits @SamKirkland ( JavaScript is not, as you may have guessed, "my jam" )

**Comment by SamKirkland** [comment]
Looks good. I'm going to give this a final test tomorrow and then merge it.

**Comment by apokalyptik** [comment]
@SamKirkland ssh host keys are not like web site SSL keys. They are generated once for a host and then stay the same unless the host replaces the server, or there is some sort of man in the middle type attack going on.  LetsEncrypt doesn't generate these. So if this setting needs changing then users should contact their hosting provider to make sure that the ssh host key did, in fact, change and that they should update their known hosts -- Probably good to review: https://www.ssh.com/ssh/host-key

**Pull request merged**
