### PR TITLE
Updated V4.3.2 to NodeJS16

### PR DESCRIPTION
**Pull request by Olzie-12**

### CODE REVIEW

**Comment by Luisisinka** [comment]
Update for node version 16  would be appreciated. Thanks

**Review by Silloky — COMMENTED** [review]
It seem fine...

**Comment by SamKirkland** [comment]
Hello. Thanks for the PR

I merged PR #338 instead because it didn't have changes to index.js
Going to cut a release soon - v4.3.3 will be using nodev16

**Comment by Olzie-12** [comment]
> Hello. Thanks for the PR
> 
> I merged PR #338 instead because it didn't have changes to index.js Going to cut a release soon - v4.3.3 will be using nodev16

No problem because sometimes when I upload the files it doesn’t actually update the needed files and i facts just replaces them with some other random jar. That’s why I made them changes as well. Hopefully you can actually fix that issue though

**Comment by SamKirkland** [comment]
@Olzie-12 can you open an issue with recreation steps and I can take a look

**Pull request closed without merging**
