### PR TITLE
delete parent and child directory same time.

### PR DESCRIPTION
**Pull request by NakagawaAtsushi**
delete parent and child directory same time.
climb folder too much after deleting directory.
removeDir function bug.

### CODE REVIEW

**Comment by SamKirkland** [comment]
Not sure if I'm following what this is doing. Wouldn't this remove folders that might have other content within them?

Also please modify the typescript files instead of the computer generated output.

**Comment by SamKirkland** [comment]
See PR #265

If you want to see how my approach differs from yours please look at the [ftp-deploy changes I made](https://github.com/SamKirkland/ftp-deploy/commit/9d37c4b78987b1bd04e47282eb2a9553eef14693)

**Comment by NakagawaAtsushi** [comment]
Thank you for your reply and bug fixes.
These code looks fine.

I sent a p-r about the removeDir bug.
https://github.com/patrickjuchli/basic-ftp/pull/207/files

**Comment by SamKirkland** [comment]
This was a bug in my usage of `basic-ftp`

**Pull request closed without merging**
